### ISSUE TITLE
Webconsole failing to install

### ISSUE THREAD

**Issue by rusher81572** [picluster/picluster#59]
unable to install on my rpi
```
root@rpi-1:~/picluster/web# npm install

> phantomjs-prebuilt@2.1.14 install /root/picluster/web/node_modules/phantomjs-prebuilt
> node install.js

module.js:487
    throw err;
    ^

Error: Cannot find module 'request-progress'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/picluster/web/node_modules/phantomjs-prebuilt/install.js:9:23)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
npm WARN picluster-webconsole@0.0.1 No description
npm WARN picluster-webconsole@0.0.1 No repository field.
npm WARN picluster-webconsole@0.0.1 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs-prebuilt@2.1.14 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs-prebuilt@2.1.14 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-07-31T22_27_59_580Z-debug.log
```

```
picluster-webconsole@0.0.1 /root/picluster/web
├─┬ body-parser@1.17.2
│ ├── bytes@2.4.0
│ ├── content-type@1.0.2
│ ├─┬ debug@2.6.7
│ │ └── ms@2.0.0
│ ├── depd@1.1.1
│ ├─┬ http-errors@1.6.1
│ │ ├── depd@1.1.0
│ │ ├── inherits@2.0.3
│ │ ├── setprototypeof@1.0.3 deduped
│ │ └── statuses@1.3.1 deduped
│ ├── iconv-lite@0.4.15
│ ├─┬ on-finished@2.3.0
│ │ └── ee-first@1.1.1
│ ├── qs@6.4.0
│ ├─┬ raw-body@2.2.0
│ │ ├── bytes@2.4.0 deduped
│ │ ├── iconv-lite@0.4.15 deduped
│ │ └── unpipe@1.0.0
│ └─┬ type-is@1.6.15
│   ├── media-typer@0.3.0
│   └─┬ mime-types@2.1.16
│     └── mime-db@1.29.0
├── casperjs@1.1.4
├── chalk@1.1.3 extraneous
├── commander@2.11.0 extraneous
├── es6-promise@4.0.5 extraneous
├── exec@0.2.1 invalid
├─┬ express@4.15.3
│ ├─┬ accepts@1.3.3
│ │ ├── mime-types@2.1.16 deduped
│ │ └── negotiator@0.6.1
│ ├── array-flatten@1.1.1
│ ├── content-disposition@0.5.2
│ ├── content-type@1.0.2 deduped
│ ├── cookie@0.3.1
│ ├── cookie-signature@1.0.6
│ ├── debug@2.6.7 deduped
│ ├── depd@1.1.1 deduped
│ ├── encodeurl@1.0.1
│ ├── escape-html@1.0.3
│ ├── etag@1.8.0
│ ├─┬ finalhandler@1.0.3
│ │ ├── debug@2.6.7 deduped
│ │ ├── encodeurl@1.0.1 deduped
│ │ ├── escape-html@1.0.3 deduped
│ │ ├── on-finished@2.3.0 deduped
│ │ ├── parseurl@1.3.1 deduped
│ │ ├── statuses@1.3.1 deduped
│ │ └── unpipe@1.0.0 deduped
│ ├── fresh@0.5.0
│ ├── merge-descriptors@1.0.1
│ ├── methods@1.1.2
│ ├── on-finished@2.3.0 deduped
│ ├── parseurl@1.3.1
│ ├── path-to-regexp@0.1.7
│ ├─┬ proxy-addr@1.1.5
│ │ ├── forwarded@0.1.0
│ │ └── ipaddr.js@1.4.0
│ ├── qs@6.4.0 deduped
│ ├── range-parser@1.2.0
│ ├─┬ send@0.15.3
│ │ ├── debug@2.6.7 deduped
│ │ ├── depd@1.1.1 deduped
│ │ ├── destroy@1.0.4
│ │ ├── encodeurl@1.0.1 deduped
│ │ ├── escape-html@1.0.3 deduped
│ │ ├── etag@1.8.0 deduped
│ │ ├── fresh@0.5.0 deduped
│ │ ├── http-errors@1.6.1 deduped
│ │ ├── mime@1.3.4
│ │ ├── ms@2.0.0 deduped
│ │ ├── on-finished@2.3.0 deduped
│ │ ├── range-parser@1.2.0 deduped
│ │ └── statuses@1.3.1 deduped
│ ├─┬ serve-static@1.12.3
│ │ ├── encodeurl@1.0.1 deduped
│ │ ├── escape-html@1.0.3 deduped
│ │ ├── parseurl@1.3.1 deduped
│ │ └── send@0.15.3 deduped
│ ├── setprototypeof@1.0.3
│ ├── statuses@1.3.1
│ ├── type-is@1.6.15 deduped
│ ├── utils-merge@1.0.0
│ └── vary@1.1.1
├── extract-zip@1.5.0 extraneous
├── font-linux@0.9.0 invalid (git+https://github.com/Lukas-W/font-linux.git#d535154e20484a9d01099beb2c89411a7e5a7e74)
├── fs-extra@1.0.0 extraneous
├── hasha@2.2.0 extraneous
├── is-my-json-valid@2.16.0 extraneous
├── jquery@3.2.1
├─┬ jquery.terminal@1.5.0
│ └── jquery@3.2.1 deduped
├── kew@0.7.0 extraneous
├── line-reader@0.4.0
├── moment@2.18.1
├─┬ node-gyp@3.6.2 invalid
│ ├── fstream@1.0.11 extraneous
│ ├── glob@7.1.2 extraneous
│ ├── graceful-fs@4.1.11 extraneous
│ ├── minimatch@3.0.4 extraneous
│ ├── mkdirp@0.5.1 extraneous
│ ├── nopt@3.0.6 extraneous
│ ├── npmlog@4.1.2 extraneous
│ ├── osenv@0.1.4 extraneous
│ ├── request@2.81.0 extraneous
│ ├── rimraf@2.6.1 extraneous
│ ├── semver@5.3.0 extraneous
│ ├── tar@2.2.1 extraneous
│ └── which@1.2.14 extraneous
├── progress@1.1.8 extraneous
├── UNMET DEPENDENCY request@
├─┬ request-debug@0.2.0 invalid
│ └── stringify-clone@1.1.1 extraneous
├── request-progress@2.0.1 extraneous
└── sys@0.0.1 invalid
```

**Comment by rusher81572** [comment]
We need to add --production and --dev to README
