### ISSUE TITLE
container-layout.html not displaying correctly

### ISSUE THREAD

**Issue by rusher81572** [picluster/picluster#70]
I can not reproduce this problem using docker-compose.yml on my laptop but I get this on the webconsole on the RaspberryPI cluster when viewing containers.I also tried removing the picluster folder and cloning again with Git.

```
rpi-5 

nginx
elasticsearch
paste
phpfpm
openvpn
throw err;
^
at Function.Module._resolveFilename (module.js:485:15)
at Function.Module._load (module.js:437:25)
at Module.require (module.js:513:17)
at require (internal/module.js:11:18)
at [eval]:1:15
at ContextifyScript.Script.runInThisContext (vm.js:44:33)
at Object.runInThisContext (vm.js:116:38)
at Object. ([eval]-wrapper:6:22)
at Module._compile (module.js:569:30)
at evalScript (bootstrap_node.js:432:27)
```

**Comment by rusher81572** [comment]
@aidanharris I resolved it by syncing node_modules from my mac to each agent node. Any idea what module is having issues?

**Comment by aidanharris** [comment]
@rusher81572 I have no idea what's going on here. It's unclear to me where this is actually throwing, I can't seem to find a "bootstrap_node.js" file. I think this could be an internal issue with node or npm. If npm continues to have issues I think we should investiage using [Yarn](https://yarnpkg.com/lang/en/docs/install/) and if that works out recommend using it over npm.
