### ISSUE TITLE
Creating a container does not work on dev branch

### ISSUE THREAD

**Issue by rusher81572** [picluster/picluster#85]
Create the container in webconsole.

```
/Users/rusher81572/picluster/server/server.js:368
            response.on('data', data => {
                    ^

TypeError: Cannot read property 'on' of null
    at Request.response [as _callback] (/Users/rusher81572/picluster/server/server.js:368:21)
    at Request.self.callback (/Users/rusher81572/picluster/server/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/Users/rusher81572/picluster/server/node_modules/request/request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/Users/rusher81572/picluster/server/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)

```

**Comment by rusher81572** [comment]
Fixed
