### ISSUE TITLE
Removing container config does not work in dev branch

### ISSUE THREAD

**Issue by rusher81572** [picluster/picluster#86]
```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.keys.forEach (/Users/rusher81572/picluster/server/server.js:728:16)
    at Array.forEach (native)
    at app.get (/Users/rusher81572/picluster/server/server.js:727:54)
    at Layer.handle [as handle_request] (/Users/rusher81572/picluster/server/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/rusher81572/picluster/server/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/rusher81572/picluster/serve
```

**Comment by rusher81572** [comment]
not seeing this a
